名字: Makefile CI

on:
  push:
    分支: [ "main" ]
  pull_request:
    分支: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - 名字: configure
      run: ./configure

    - 名字: Install dependencies
      run: make

    - 名字: Run check
      run: make check

    - 名字: Run distcheck
      run: make distcheck
